onnx_file_path: ""
prototxt_file_path: ""
caffemodel_file_path: ""
image_folder_path: ""
config_file_path: ""
model_name: "resnet18_track_detection"
model_type: "onnx"
dimension_type: "224x224"
width: 224
height: 224

input_type_rt: "nv12"
input_layout_rt: "None"
input_type_train: "rgb"
input_layout_train: "NCHW"
norm_type: "data_mean_and_scale"
has_model: "true"
mean_value_array: [123.675, 116.28, 103.53]
scale_value_array: [0.0171248, 0.017507, 0.0174292]

detect_model: "quantized_model"
detect_image_file_path: ""
epochs: 4
batch_size: 8

dataset_file_path: ""
data_path: "/root/tool_chain_temporary" #Path for storing uploaded and generated files
temporary_path: ""